#!/bin/bash
# SessionStart hook — prepares a Claude Code on the web container for chill-dogs.
#
# Does three things:
#   1. Installs Bun dependencies (node_modules is not in the repo).
#   2. Materializes .env from environment variables set on the Claude Code
#      environment, so Astro's import.meta.env sees them the same way the
#      scripts see process.env.
#   3. Prints a readiness report so the agent knows which integration scripts
#      can actually run in this container.
#
# Never fails the session: every step is best-effort and reports instead of
# exiting non-zero.
set -uo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$PROJECT_DIR" || exit 0

# Local machines already have their own setup; this hook is for web containers.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

echo "[chill-dogs] Setting up session in $PROJECT_DIR"

# --- 1. Dependencies -------------------------------------------------------
# Plain `bun install` (not --frozen-lockfile) so the resolved node_modules is
# reused from the cached container state on subsequent sessions.
if command -v bun >/dev/null 2>&1; then
  echo "[chill-dogs] bun $(bun --version) — installing dependencies..."
  bun install || echo "[chill-dogs] WARNING: bun install failed"
else
  echo "[chill-dogs] WARNING: bun not found on PATH; install from https://bun.sh"
fi

# --- 2. .env from environment variables ------------------------------------
# Astro reads .env via Vite; the CLI scripts read process.env. Writing the
# values the environment supplies into .env makes both paths agree.
ENV_KEYS=(
  PUBLIC_SITE_URL
  PUBLIC_POSTHOG_KEY
  PUBLIC_POSTHOG_HOST
  PUBLIC_PINTEREST_TAG_ID
  PUBLIC_BUTTONDOWN_USERNAME
  PUBLIC_BUTTONDOWN_FORM_ACTION
  MAINTENANCE_MODE
  SERP_API_KEY
  SEARCHAPI_KEY
  INDEXNOW_KEY
  INDEXNOW_ENDPOINT
  INDEXNOW_SITE_ORIGIN
  INDEXNOW_DRY_RUN
  IMPACT_ACCOUNT_SID
  IMPACT_AUTH_TOKEN
  CHEWY_IMPACT_CAMPAIGN_ID
  CHEWY_IMPACT_CATALOG_ID
  CHEWY_IMPACT_AD_ID
  CHEWY_IMPACT_BASE_URL
)

if [ -f .env ]; then
  echo "[chill-dogs] .env already exists — leaving it untouched"
else
  written=0
  tmp_env="$(mktemp)"
  {
    echo "# Generated by .claude/hooks/session-start.sh from environment variables."
    echo "# Edit the Claude Code environment config to change these, not this file."
  } >> "$tmp_env"
  for key in "${ENV_KEYS[@]}"; do
    value="${!key:-}"
    if [ -n "$value" ]; then
      echo "${key}=${value}" >> "$tmp_env"
      written=$((written + 1))
    fi
  done
  if [ "$written" -gt 0 ]; then
    mv "$tmp_env" .env
    echo "[chill-dogs] Wrote .env with $written variable(s) from the environment"
  else
    rm -f "$tmp_env"
    echo "[chill-dogs] No integration variables set in the environment — skipped .env"
  fi
fi

# Default the site URL so OG/canonical URLs build correctly even with no config.
if [ -z "${PUBLIC_SITE_URL:-}" ] && [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  echo 'export PUBLIC_SITE_URL="https://www.chill-dogs.com"' >> "$CLAUDE_ENV_FILE"
fi

# --- 3. Warm the build -----------------------------------------------------
# `bun run test` builds first because the seo-meta test reads dist/. Building
# here means a fresh session can run vitest directly, and the warm dist/ and
# .astro/ are captured in the cached container state.
if [ "${CHILL_DOGS_SKIP_BUILD:-}" != "true" ] && command -v bun >/dev/null 2>&1; then
  echo "[chill-dogs] Warming the static build..."
  if bun run build > /tmp/chill-dogs-build.log 2>&1; then
    echo "[chill-dogs] Build OK — dist/ is ready, vitest can run directly"
  else
    echo "[chill-dogs] WARNING: build failed; see /tmp/chill-dogs-build.log"
    tail -20 /tmp/chill-dogs-build.log
  fi
fi

# --- 4. Readiness report ---------------------------------------------------
report_script() {
  local label="$1"
  shift
  local missing=()
  for key in "$@"; do
    [ -z "${!key:-}" ] && missing+=("$key")
  done
  if [ ${#missing[@]} -eq 0 ]; then
    echo "[chill-dogs]   ready:   $label"
  else
    echo "[chill-dogs]   missing: $label — needs ${missing[*]}"
  fi
}

echo "[chill-dogs] Integration script readiness:"
report_script "bun run check:amazon (local cache only)"
report_script "bun run check:asins (needs egress to amazon.com)"
report_script "bun run fetch:chewy" IMPACT_ACCOUNT_SID IMPACT_AUTH_TOKEN CHEWY_IMPACT_CAMPAIGN_ID
report_script "bun run chewy-link" IMPACT_ACCOUNT_SID IMPACT_AUTH_TOKEN CHEWY_IMPACT_CAMPAIGN_ID CHEWY_IMPACT_AD_ID
report_script "scripts/fetch-amazon-data.ts (SerpAPI)" SERP_API_KEY
report_script "scripts/fetch-amazon-data.ts (SearchAPI)" SEARCHAPI_KEY
report_script "bun run indexnow:submit" INDEXNOW_KEY

echo "[chill-dogs] Scripts that call out to amazon.com, serpapi.com, searchapi.io,"
echo "[chill-dogs] api.impact.com, chewy.com, or api.indexnow.org need those hosts"
echo "[chill-dogs] on the environment's network allowlist. See docs/ai/engineering/environment-and-integrations.md"

exit 0
