#!/bin/bash
# SessionStart hook — prepares a Claude Code on the web container for chill-dogs.
#
# Does three things:
#   1. Installs Bun dependencies (node_modules is not in the repo).
#   2. Materializes .env from environment variables set on the Claude Code
#      environment, so Astro's import.meta.env sees them the same way the
#      scripts see process.env.
#   3. Prints a readiness report so the agent knows which integration scripts
#      can actually run in this container.
#
# Never fails the session: every step is best-effort and reports instead of
# exiting non-zero.
set -uo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "$PROJECT_DIR" || exit 0

# Local machines already have their own setup; this hook is for web containers.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

echo "[chill-dogs] Setting up session in $PROJECT_DIR"

# --- 1. Dependencies -------------------------------------------------------
# Plain `bun install` (not --frozen-lockfile) so the resolved node_modules is
# reused from the cached container state on subsequent sessions.
if command -v bun >/dev/null 2>&1; then
  echo "[chill-dogs] bun $(bun --version) — installing dependencies..."
  bun install || echo "[chill-dogs] WARNING: bun install failed"
else
  echo "[chill-dogs] WARNING: bun not found on PATH; install from https://bun.sh"
fi

# --- 2. .env from environment variables ------------------------------------
# Astro reads .env via Vite; the CLI scripts read process.env. Writing the
# values the environment supplies into .env makes both paths agree.
ENV_KEYS=(
  PUBLIC_SITE_URL
  PUBLIC_POSTHOG_KEY
  PUBLIC_POSTHOG_HOST
  PUBLIC_PINTEREST_TAG_ID
  PUBLIC_BUTTONDOWN_USERNAME
  PUBLIC_BUTTONDOWN_FORM_ACTION
  MAINTENANCE_MODE
  SERP_API_KEY
  SEARCHAPI_KEY
  INDEXNOW_KEY
  INDEXNOW_ENDPOINT
  INDEXNOW_SITE_ORIGIN
  INDEXNOW_DRY_RUN
  IMPACT_ACCOUNT_SID
  IMPACT_AUTH_TOKEN
  CHEWY_IMPACT_CAMPAIGN_ID
  CHEWY_IMPACT_CATALOG_ID
  CHEWY_IMPACT_AD_ID
  CHEWY_IMPACT_BASE_URL
)

if [ -f .env ]; then
  echo "[chill-dogs] .env already exists — leaving it untouched"
else
  written=0
  tmp_env="$(mktemp)"
  {
    echo "# Generated by .claude/hooks/session-start.sh from environment variables."
    echo "# Edit the Claude Code environment config to change these, not this file."
  } >> "$tmp_env"
  for key in "${ENV_KEYS[@]}"; do
    value="${!key:-}"
    if [ -n "$value" ]; then
      echo "${key}=${value}" >> "$tmp_env"
      written=$((written + 1))
    fi
  done
  if [ "$written" -gt 0 ]; then
    mv "$tmp_env" .env
    echo "[chill-dogs] Wrote .env with $written variable(s) from the environment"
  else
    rm -f "$tmp_env"
    echo "[chill-dogs] No integration variables set in the environment — skipped .env"
  fi
fi

if [ -n "${CLAUDE_ENV_FILE:-}" ]; then
  # Default the site URL so OG/canonical URLs build correctly with no config.
  if [ -z "${PUBLIC_SITE_URL:-}" ]; then
    echo 'export PUBLIC_SITE_URL="https://www.chill-dogs.com"' >> "$CLAUDE_ENV_FILE"
  fi

  # Node 22's built-in fetch ignores HTTPS_PROXY unless this is set. Without it
  # the .mjs scripts (indexnow-submit, the OG image fetches) cannot reach any
  # host when the container routes egress through a proxy.
  if [ -n "${HTTPS_PROXY:-}" ] && [ -z "${NODE_USE_ENV_PROXY:-}" ]; then
    echo 'export NODE_USE_ENV_PROXY=1' >> "$CLAUDE_ENV_FILE"
  fi
fi

# --- 3. Warm the build -----------------------------------------------------
# `bun run test` builds first because the seo-meta test reads dist/. Building
# here means a fresh session can run vitest directly, and the warm dist/ and
# .astro/ are captured in the cached container state.
if [ "${CHILL_DOGS_SKIP_BUILD:-}" != "true" ] && command -v bun >/dev/null 2>&1; then
  echo "[chill-dogs] Warming the static build..."
  if bun run build > /tmp/chill-dogs-build.log 2>&1; then
    echo "[chill-dogs] Build OK — dist/ is ready, vitest can run directly"
  else
    echo "[chill-dogs] WARNING: build failed; see /tmp/chill-dogs-build.log"
    tail -20 /tmp/chill-dogs-build.log
  fi
fi

# --- 4. Readiness report ---------------------------------------------------
# A script can fail for three independent reasons, so all three are checked:
# missing credentials, a host the egress policy blocks, and an HTTP client that
# cannot use the proxy. Reporting only on credentials calls a script "ready"
# when it cannot reach anything.

# Reachability: probed in parallel so the whole sweep costs one timeout, not six.
probe_host() {
  local host="$1"
  local out="$2"
  # --head keeps the probe cheap; any HTTP status counts as reachable, since
  # only the CONNECT tunnel is being tested. A blocked host fails the tunnel
  # (curl exit 56, "CONNECT tunnel failed, response 403").
  if curl -sS -I -o /dev/null -m 6 "https://${host}" 2>/dev/null; then
    echo "reachable" > "$out"
  else
    echo "BLOCKED" > "$out"
  fi
}

HOSTS=(www.amazon.com serpapi.com www.searchapi.io api.impact.com www.chewy.com api.indexnow.org)
probe_dir="$(mktemp -d)"
for host in "${HOSTS[@]}"; do
  probe_host "$host" "$probe_dir/$host" &
done
wait

blocked_hosts=()
host_state() {
  cat "$probe_dir/$1" 2>/dev/null || echo BLOCKED
}
for host in "${HOSTS[@]}"; do
  [ "$(host_state "$host")" = "BLOCKED" ] && blocked_hosts+=("$host")
done

# Runtime: Bun's fetch cannot complete the TLS handshake inside a proxy CONNECT
# tunnel — it fails ECONNRESET against every allowlisted host, while Node's
# fetch (with NODE_USE_ENV_PROXY=1) and curl succeed against the same hosts.
# So in a proxied container the Bun-based scripts cannot make network calls
# even when their hosts are reachable. Verified on bun 1.3.11.
bun_net_broken=false
[ -n "${HTTPS_PROXY:-}" ] && bun_net_broken=true

# report_script <label> <runtime: bun|node|none> <host or -> [env keys...]
report_script() {
  local label="$1" runtime="$2" host="$3"
  shift 3
  local missing=()
  for key in "$@"; do
    [ -z "${!key:-}" ] && missing+=("$key")
  done

  if [ ${#missing[@]} -gt 0 ]; then
    echo "[chill-dogs]   no-keys:  $label — needs ${missing[*]}"
  elif [ "$host" != "-" ] && [ "$(host_state "$host")" = "BLOCKED" ]; then
    echo "[chill-dogs]   blocked:  $label — $host is off the network allowlist"
  elif [ "$host" != "-" ] && [ "$runtime" = "bun" ] && [ "$bun_net_broken" = true ]; then
    echo "[chill-dogs]   no-proxy: $label — bun fetch cannot use this container's proxy"
  else
    echo "[chill-dogs]   ready:    $label"
  fi
}

echo "[chill-dogs] Integration script readiness:"
report_script "bun run check:amazon (local cache only)" none -
report_script "bun run check:asins" bun www.amazon.com
report_script "bun run fetch:chewy" bun api.impact.com IMPACT_ACCOUNT_SID IMPACT_AUTH_TOKEN CHEWY_IMPACT_CAMPAIGN_ID
report_script "bun run chewy-link" bun api.impact.com IMPACT_ACCOUNT_SID IMPACT_AUTH_TOKEN CHEWY_IMPACT_CAMPAIGN_ID CHEWY_IMPACT_AD_ID
report_script "scripts/fetch-amazon-data.ts (SerpAPI)" bun serpapi.com SERP_API_KEY
report_script "scripts/fetch-amazon-data.ts (SearchAPI)" bun www.searchapi.io SEARCHAPI_KEY
report_script "bun run indexnow:submit" node api.indexnow.org INDEXNOW_KEY

rm -rf "$probe_dir"

if [ ${#blocked_hosts[@]} -gt 0 ]; then
  echo "[chill-dogs] Blocked hosts: ${blocked_hosts[*]}"
  echo "[chill-dogs] Add them under Environment settings → Network access."
fi

if [ "$bun_net_broken" = true ]; then
  echo "[chill-dogs] Anything marked no-proxy runs in GitHub Actions instead:"
  echo "[chill-dogs] .github/workflows/integration-checks.yml (workflow_dispatch)."
fi

echo "[chill-dogs] Details: docs/ai/engineering/environment-and-integrations.md"

exit 0
